"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3x&^=we=xgdx$xt-z)vxvzai*8b9f!2=%%*44ngc6_4(9gft+t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

import os
#SETTINGS_PATH = os.path.dirname(os.path.dirname(__file__))



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'eco',
    'members',
    'django_saml',
]

AUTHENTICATION_BACKENDS = [
    'django_saml.backends.SamlUserBackend',
]



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecommerce.urls'

import os
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce.wsgi.application'



# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/saml/login'

APPEND_SLASH = True


SAML_SP = {
    "entityId": "https://127.0.0.1:8000/saml/metadata/",
    "assertionConsumerService": {
        "url": "https://127.0.0.1:8000/saml/acs/",
        # DO NOT CHANGE THIS
        "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
    },
    "singleLogoutService": {
        "url": "https://127.0.0.1:8000/saml/sls/",
        # DO NOT CHANGE THIS
        "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
    },
    "NameIDFormat": "urn:oasis:names:tc:SAML:2.0:nameid-format:unspecified",
    "x509cert": "<can also be loaded by file, see SAML_BASE_DIRECTORY>",
    "privateKey": "<can also be loaded by file, see SAML_BASE_DIRECTORY>"
}




SAML_IDP = {
    "entityId": "https://sso.sdm.im.ntu.edu.tw/saml2/idp/metadata.php",
    "singleSignOnService": {
        "url": "https://sso.sdm.im.ntu.edu.tw/saml2/idp/SSOService.php",
        "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
    },
    "singleLogoutService": {
        "url": "https://sso.sdm.im.ntu.edu.tw/saml2/idp/SingleLogoutService.php",
        "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
    },
    "x509cert": "MIIEAzCCAuugAwIBAgIJAIDHA9QoK1uLMA0GCSqGSIb3DQEBCwUAMIGXMQswCQYDVQQGEwJ0dzEPMA0GA1UECAwGdGFpd2FuMQ8wDQYDVQQHDAZ0YWlwZWkxIzAhBgNVBAoMGk5hdGlvbmFsIFRhaXdhbiBVbml2ZXJzaXR5MSUwIwYDVQQLDBxJbmZvcm1hdGlvbiBNYW5hZ2VtZW50IERlcHQuMRowGAYDVQQDDBFzZG0uaW0ubnR1LmVkdS50dzAeFw0xNTEyMDEyMzI4MzZaFw0yNTExMzAyMzI4MzZaMIGXMQswCQYDVQQGEwJ0dzEPMA0GA1UECAwGdGFpd2FuMQ8wDQYDVQQHDAZ0YWlwZWkxIzAhBgNVBAoMGk5hdGlvbmFsIFRhaXdhbiBVbml2ZXJzaXR5MSUwIwYDVQQLDBxJbmZvcm1hdGlvbiBNYW5hZ2VtZW50IERlcHQuMRowGAYDVQQDDBFzZG0uaW0ubnR1LmVkdS50dzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALj0FOPN3nzFUXyE63uXGb5ZH8i55qWXPamrMeKxQOcc+Wn3E/b5GQ7geEgwoC34McAO8NBIXQpfLprIq+x0osE0IEbnDRMEu1gi+Rf9ZgQpZm/5gPN1pNQ1mYiCFkyebIYq8q1itlYu9Kn2M2Iqraoa6yRC48vjIS/NsBJ/5vq/UFgib6m78yAnxPW7IcdUkCnrjAKoKJnbxyJVhYJlo3QTS8VF8fYkse/HU9DpE1FNKJnmOcOhyQDZykjxATQ4wT472+Zk9W1bp2WXsCPN5uMUjN+pKOX1PdQH5TyWKVZ+1zrG3VK5Owupo/gD5TZxAueMcLJAGcYUuW/u8X3g97MCAwEAAaNQME4wHQYDVR0OBBYEFIoL6EqeXA/OqiqAAKE6DrsjAXNhMB8GA1UdIwQYMBaAFIoL6EqeXA/OqiqAAKE6DrsjAXNhMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAHp/Ky/dR3W8x4bYSBTJvlmMRRZbsvSgqeuLs7SYCNZIUju4uyyUkHcWwsYA0aLOD695wr+Ri1zI8Ms3ypUNt0+ZZIfqdQiKwNU4WIK8m19ieIdgo/Iy3m9hKnwxhhWHTCaTQDtOsv4SuVCTOEsM80b0zRyPmGFozaX+lp6hUIJvC7KjHw7H+Q3VnIbgoVOEMN8WfcAHmftYoqg1XzARVvVylKjIjzD3mHIQSab8FI3SttsY3/Nx54BGy07il8Lzd+fK1H0sZR7l3gFbVbDWuMJnw5arT9WwxjYAyPpEFUHuCtziwN7R1U83vJErD0eGvB+lfWmrdQIvq6AVo83/0ZM="
}
SAML_IDP_FILE = os.path.join(BASE_DIR, 'idp_meta.xml')
SAML_IDP_URL = 'https://sso.sdm.im.ntu.edu.tw/saml2/idp/metadata.php'


SAML_SECURITY = {
    "nameIdEncrypted": False,
    "authnRequestsSigned": False,
    "logoutRequestSigned": False,
    "logoutResponseSigned": False,
    "signMetadata": False,
    "wantMessagesSigned": False,
    "wantAssertionsSigned": False,
    "wantNameId": True,
    "wantNameIdEncrypted": False,
    "wantAssertionsEncrypted": False,
    "signatureAlgorithm": "http://www.w3.org/2000/09/xmldsig#rsa-sha1",
    "digestAlgorithm": "http://www.w3.org/2000/09/xmldsig#sha1"
}
